<Project>
  <PropertyGroup>
    <VersionPrefix>1.2.1</VersionPrefix>
    <Product>SSH Key Deployer</Product>
    <Authors>tuolaji996</Authors>
    <RepositoryUrl>https://github.com/tuolaji996/windows-ssh-key-deployer</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <NeutralLanguage>zh-Hans</NeutralLanguage>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
  </PropertyGroup>
</Project>
